@startuml 演習6-3_ステートマシン図_診察予約システム.pu
state メニュー
state 予約と確認
state あなたの順番
state 今の順番
[*] -right-> メニュー :接続する
メニュー -right-> [*] :終了する
メニュー --> 予約と確認 :予約する
予約と確認 --> メニュー :取り消しボタンを押す
予約と確認 -right-> あなたの順番 :登録ボタンを押す
予約と確認 -right-> あなたの順番 :確認ボタンを押す
あなたの順番 -up-> メニュー :あなたの順番を表示する
今の順番 --> メニュー :今の順番を探す
メニュー --> 今の順番 :今の順番を増やす
@enduml