@startuml 演習3-3_CL_ホテルと利用者と部屋と予約.pu
class 利用者 {
    - 名前
    - 住所
    - 電話番号
}

class ホテル {
    - 部屋
}

class 部屋 {
    - タイプ
    - 価格
    - キャンペーン価格
}

class 予約 {
    - チェックイン日
    - 滞在時間
    - 値段
}
利用者 o-ri- 予約
予約 -down- 部屋
ホテル *-ri- 部屋