@startuml 演習6-5-1_クラス図_ライントレーサー.pu
class ライントレーサー
class 光センサー
class 右モータ
class 左モータ
class CPU
class 電源SW

ライントレーサー "1"*-up- 光センサー
ライントレーサー "1"*-ri- 右モータ
ライントレーサー "1"*-le- 左モータ
ライントレーサー "1"*-- CPU
ライントレーサー "1"*-- 電源SW
@enduml
